### ISSUE TITLE
test_empty_env fails w/ Gentoo sandbox

### ISSUE THREAD

**Issue by mgorny** [google/python-subprocess32#23]
Gentoo sandbox enforces itself into child processes, and therefore the environment is not empty:

```
======================================================================
FAIL: test_empty_env (__main__.ProcessTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_subprocess32.py", line 545, in test_empty_env
    self.assertEqual(stdout.strip(), "[]")
AssertionError: "['LD_PRELOAD', 'SANDBOX_READ', 'SANDBOX_MESSAGE_P@TH', 'SANDBOX_ON', 'SANDBOX_DENY', 'SANDBOX_VERBOSE', 'SANDBOX_LOG', 'SANDBOX_PREDICT', 'SANDBOX_DEBUG_LOG', 'SANDBOX_ACTIVE', 'SANDBOX_WRITE']" != '[]'

======================================================================
FAIL: test_empty_env (__main__.ProcessTestCasePOSIXPurePython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_subprocess32.py", line 545, in test_empty_env
    self.assertEqual(stdout.strip(), "[]")
AssertionError: "['LD_PRELOAD', 'SANDBOX_READ', 'SANDBOX_MESSAGE_P@TH', 'SANDBOX_ON', 'SANDBOX_DENY', 'SANDBOX_VERBOSE', 'SANDBOX_LOG', 'SANDBOX_PREDICT', 'SANDBOX_DEBUG_LOG', 'SANDBOX_ACTIVE', 'SANDBOX_WRITE']" != '[]'

======================================================================
FAIL: test_empty_env (__main__.ProcessTestCaseNoPoll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_subprocess32.py", line 545, in test_empty_env
    self.assertEqual(stdout.strip(), "[]")
AssertionError: "['LD_PRELOAD', 'SANDBOX_READ', 'SANDBOX_MESSAGE_P@TH', 'SANDBOX_ON', 'SANDBOX_DENY', 'SANDBOX_VERBOSE', 'SANDBOX_LOG', 'SANDBOX_PREDICT', 'SANDBOX_DEBUG_LOG', 'SANDBOX_ACTIVE', 'SANDBOX_WRITE']" != '[]'

----------------------------------------------------------------------
Ran 264 tests in 197.918s

FAILED (failures=3)
```

**Comment by gpshead** [comment]
This sounds like a minor issue due to a non-standard execution environment. A PR to extend the list of environment variables that are ignored in that test would be accepted.  (some are already ignored due to MacOS behavior)

**Comment by mgorny** [comment]
Well, the change is trivial obviously:

```diff
diff --git a/test_subprocess32.py b/test_subprocess32.py
index f66fa51..451d388 100644
--- a/test_subprocess32.py
+++ b/test_subprocess32.py
@@ -586,11 +586,14 @@ class ProcessTestCase(BaseTestCase):
     def test_empty_env(self):
         # Note: This excludes some __CF_* and VERSIONER_* keys OS X insists
         # on adding even when the environment in exec is empty.
+        # Plus LD_PRELOAD and SANDBOX_* forced by Gentoo Sandbox.
         p = subprocess.Popen(
                 [sys.executable, "-c",
                  'import os; '
                  'print([k for k in os.environ.keys() '
-                 '       if ("VERSIONER" not in k and "__CF" not in k)])'],
+                 '       if ("VERSIONER" not in k and "__CF" not in k and'
+                 '           not k.startswith("SANDBOX_")) and'
+                 '           k != "LD_PRELOAD"])'],
                 stdout=subprocess.PIPE, env={})
         try:
             stdout, stderr = p.communicate()
```

I can submit a pull request but I'm not interested in signing a CLA considering how absurd amount of private information Google demands for it.

**Comment by mgorny** [comment]
Thanks!
