### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Signals'

### ISSUE THREAD

**Issue by jwilk** [google/python-subprocess32#49]
This happens with `subprocess32==3.5.0`:
```pycon
>>> import subprocess32 as s32
>>> exc = s32.CalledProcessError(-1, "eggs")
>>> raise exc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
subprocess32.CalledProcessError: <exception str() failed>
>>> str(exc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jwilk/.local/lib/python2.7/site-packages/subprocess32.py", line 72, in __str__
    self.cmd, signal.Signals(-self.returncode))
AttributeError: 'module' object has no attribute 'Signals'
```

Aside from bugginess, I wonder why this code is there in the first place.
subprocess uses `signal.Signals` only since Python 3.6, whereas subprocess32 is supposed to be 3.2 with some 3.3 and 3.5 backports.

**Comment by gpshead** [comment]
That must've been missed when backporting the code, it doesn't look like that path is covered by a test. fixing...

**Comment by gpshead** [comment]
3.5.1 released.
